import { Inter } from "next/font/google";
import "./(styles)/globals.scss";

import Header from "./header";
import Footer from "./footer";
import Breadcrumbs from "./breadcrumbs";

const inter = Inter({ subsets: ["latin"] });
const envVr = process.env.TEST_TEXT || "no env";

export const metadata = {
  viewport: "width=device-width, initial-scale=1",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  //
  //console.log("props", props);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* {bread} */}
        <Breadcrumbs envVr={envVr} />
        <main>{props.children}</main>
        <Footer />
      </body>
    </html>
  );
}
